### ISSUE TITLE
点击三次会弹出搜索框

### ISSUE THREAD

**Issue by DullCat-c** [androiddevelop/hexo-search#1]
感谢作者的分享, 我突然发现点击三次会弹出搜索款,但是我并不想要这么做,我应该怎么去关闭这个操作呢?

**Comment by androiddevelop** [comment]
点击三次的操作指的是?

**Comment by DullCat-c** [comment]
就是在页面空白处连续点击鼠标左键三次

**Comment by androiddevelop** [comment]
试了一下，没出来该情况，方便的话提供下博客地址

**Comment by DullCat-c** [comment]
我的博客地址:http://blog.dullcat.top/
我开始也以为是我可能弄了什么导致的,但是我在您的博客上也测试出了相同的结论.

**Comment by androiddevelop** [comment]
我这边在mac上试了下没问题，你的系统以及浏览器环境是? 或者加个QQ具体对下1373989587

**Comment by DullCat-c** [comment]
谷歌浏览器,win10系统,qq已经加了

**Comment by androiddevelop** [comment]
已经沟通解决
